### ISSUE TITLE
关于游戏窗口对齐

### ISSUE THREAD

**Issue by lzcndm** [SuHaoXD/yysAuto#1]
调用win32gui.SetWindowPos()函数可以指定对齐的坐标，比人为对齐要精确，不过需要管理员权限打开cmd。顺便问下，作者有收到鬼使黑来信吗？

**Comment by SuHaoXD** [comment]
感谢分享。使用win32gui.MoveWindow(handle,-7,0,1136,640,True)好像更加方便。本来鼠标操作就需要管理员权限。前段时间挂了几百张御灵肝绘卷  到目前没有鬼使黑

**Comment by lzcndm** [comment]
主要SetWindowPos可以顺便调整窗口大小。再顺便问下，未来会出组队模式吗？
